version: "3.4"

services:
    db:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: azerty
        volumes:
            - ./data/mysql:/data
    pma:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        environment:
            MYSQL_ROOT_PASSWORD: azerty
            PMA_HOST: db
        ports:
            - 8001:80
    php:
        build:
            context: .
            dockerfile: docker/symfony/Dockerfile
            target: fingz_php_dev
        depends_on:
            - db
        volumes:
            - ./docker/symfony/etc/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./docker/symfony/etc/php/php-cli.ini:/usr/local/etc/php/php-cli.ini:ro
            - ./app/symfony/src:/srv/symfony/src:rw
            - ./app/symfony/config:/srv/symfony/config:rw
            - ./app/symfony/templates:/srv/symfony/templates:rw
            - ./app/symfony/public:/srv/symfony/public:rw
            - ./app/symfony/vendor:/srv/symfony/vendor:rw
    nginx:
        image: nginx:alpine
        depends_on:
            - php
        volumes:
            - ./docker/symfony/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./app/symfony/public:/srv/symfony/public:ro
        ports:
            - 8080:80
    reactjs:
        build:
            context: .
            dockerfile: docker/reactjs/Dockerfile
            target: fingz_client_nginx
        depends_on:
            - nginx
        ports:
            - 8087:80
    mailhog:
        image: mailhog/mailhog
        logging:
            driver: "none"
        ports:
            - 1025:1025
            - 8025:8025
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
        environment:
            - "discovery.type=single-node"
            - "bootstrap.memory_lock=true"
            - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
            - "xpack.security.enabled=false"
            - "http.cors.enabled=true"
            - "http.cors.allow-origin=*"
        ports:
            - 9200:9200
    elasticsearch-head:
        depends_on:
            - elasticsearch
        image: tobias74/elasticsearch-head:6
        ports:
            - 9100:9100
    mercure:
        image: dunglas/mercure:legacy-v0.11.0-beta.2
        container_name: mercure
        environment:
            JWT_KEY: UQh6d22mN6zRMK72wcoW4R8M0Re0qgz3
            ALLOW_ANONYMOUS: 1
            PUBLISH_ALLOWED_ORIGINS: http://localhost:88
            CORS_ALLOWED_ORIGINS: '*'
            DEBUG: 1
        ports:
            - "3001:80"
        expose:
            - "3001"
